[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"

]
live_config_reload = true

[cursor]
unfocused_hollow = true

  [cursor.style]
  shape = "Block"
  blinking = "Off"

[font]
size = 12

[window]
opacity = 0.8
